### ISSUE TITLE
流程圖

### ISSUE THREAD

**Issue by KrissWong** [ntuaha/GodzillaAlert#18]
流程圖v2.0
http://www.pinterest.com/kryvaliun1129/godzilla_alert/

粉蝨專業也有
https://www.facebook.com/media/set/?set=a.1526342020968524.1073741828.1526293307640062&type=3

**Comment by suensummit** [comment]
粉蝨專業很癢der港覺

**Comment by KrissWong** [comment]
新增頁面 flow.html

**Comment by ntuaha** [comment]
差不多完成, 之後要修再開新issue
