### ISSUE TITLE
安裝NodeJS

### ISSUE THREAD

**Issue by ntuaha** [ntuaha/GodzillaAlert#9]
- [x] 大家都可以使用

**Comment by suensummit** [comment]
![Uploading Screen Shot 2015-01-03 at 9.49.29 PM.png . . .]()

**Comment by suensummit** [comment]
Done!

![screen shot 2015-01-04 at 1 59 36 am](https://cloud.githubusercontent.com/assets/5906989/5603233/7655ed12-93b5-11e4-8d8f-e3e5d47449e1.png)

**Comment by suensummit** [comment]
```
$ node -v
$ nodejs -v
```

Both works well!

![screen shot 2015-01-04 at 2 02 29 am](https://cloud.githubusercontent.com/assets/5906989/5603235/c8b7aabe-93b5-11e4-87ed-99a178e72ca2.png)
